{% set name = "jupysql-plugin" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupysql_plugin-{{ version }}.tar.gz
  sha256: 7085e178898ee012f4d339f5d356432332a5daa9080ec4cdb3064e0ace7894d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4.0.0
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - pip
  run:
    - python >={{ python_min }}
    - ploomber-core
    - jupyter_server

test:
  imports:
    - jupysql_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ploomber/jupysql-plugin
  summary: Jupyterlab extension for JupySQL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - edublancas
    - neelasha23
